name: deploy

on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order

      - uses: actions/checkout@v3
      - name: gradle bootJar
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - name: kill 8080 port if exist
        run: |
          if lsof -i :8080; then
            echo "Port 8080 is already in use. Killing the process..."
            lsof -i :8080 | awk 'NR!=1 {print $2}' | xargs kill -9
          fi

      - name: deploy
        run: |
          sudo java -jar build/libs/jwp-shopping-order.jar &
